package com.winterchen.webservice.client.webservice.user;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2021-12-16T17:38:44.129+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "userInfoService",
                  wsdlLocation = "classpath:wsdl/user.wsdl",
                  targetNamespace = "http://user.winterchen.com/webservice")
public class UserInfoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://user.winterchen.com/webservice", "userInfoService");
    public final static QName UserInfoName = new QName("http://user.winterchen.com/webservice", "userInfoName");
    static {
        URL url = UserInfoService.class.getClassLoader().getResource("wsdl/user.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(UserInfoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/user.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserInfoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserInfoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UserInfoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserInfoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UserInfoType
     */
    @WebEndpoint(name = "userInfoName")
    public UserInfoType getUserInfoName() {
        return super.getPort(UserInfoName, UserInfoType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserInfoType
     */
    @WebEndpoint(name = "userInfoName")
    public UserInfoType getUserInfoName(WebServiceFeature... features) {
        return super.getPort(UserInfoName, UserInfoType.class, features);
    }

}
