package com.winterchen.webservice.client.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2021-12-16T13:45:30.620+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://www.winterchen.com/webservice", name = "authorPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthorPortType {

    @WebMethod
    @RequestWrapper(localName = "getAuthorString", targetNamespace = "http://www.winterchen.com/webservice", className = "com.winterchen.webservice.client.webservice.GetAuthorString")
    @ResponseWrapper(localName = "getAuthorStringResponse", targetNamespace = "http://www.winterchen.com/webservice", className = "com.winterchen.webservice.client.webservice.GetAuthorStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getAuthorString(
        @WebParam(name = "authorName", targetNamespace = "")
        String authorName
    );

    @WebMethod
    @RequestWrapper(localName = "getAuthorList", targetNamespace = "http://www.winterchen.com/webservice", className = "com.winterchen.webservice.client.webservice.GetAuthorList")
    @ResponseWrapper(localName = "getAuthorListResponse", targetNamespace = "http://www.winterchen.com/webservice", className = "com.winterchen.webservice.client.webservice.GetAuthorListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<AuthorDto> getAuthorList();

    @WebMethod
    @RequestWrapper(localName = "getAuthorByName", targetNamespace = "http://www.winterchen.com/webservice", className = "com.winterchen.webservice.client.webservice.GetAuthorByName")
    @ResponseWrapper(localName = "getAuthorByNameResponse", targetNamespace = "http://www.winterchen.com/webservice", className = "com.winterchen.webservice.client.webservice.GetAuthorByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AuthorDto getAuthorByName(
        @WebParam(name = "authorName", targetNamespace = "")
        String authorName
    );
}
