cxf:
  path: /ws

spring:
  application:
    name: webwervice-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    async:
      request-timeout:
        seconds: 9000000000000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/py_test?autoReconnect=true&useSSL=false&characterEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useServerPrepStmts=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
    # 监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
    filters: stat
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
server:
  port: 8082


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.winterchen.webservice.service.entity
  configuration:
    map-underscore-to-camel-case: false
    jdbc-type-for-null: 'null'

